services:
  app:
    build: .
    container_name: shortener
    ports:
      - "3000:$PORT"
    networks:
      - shortener
    env_file:
      - .env
    restart: always
    depends_on:
      - redis

  redis:
    image: "redis:alpine"
    container_name: redis
    restart: always
    healthcheck:
      test: ["CMD", "redis-cli", "--raw", "incr", "ping"]
    networks:
      - shortener
    volumes:
      - redisdata:/root/redis
    env_file:
      - .env

networks:
  shortener:
    name: shortener
    driver: bridge

volumes:
  redisdata:
